

1. Write a function to compute 5/0 and use try/except to catch the exceptions.



In [0]:
def divide_by_zero():
  return 5/0

try:
  divide_by_zero()
except ZeroDivisionError  as zeroerror:
  print('Handle error', zeroerror)
except:
  print('any othe expression')  



Handle error division by zero


#### 2. Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

Output should come as below:

Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.




In [0]:
# Using List comprehension
subjects=["Americans","Indians"]
verbs=["play","watch"] 
objects=["Baseball","Cricket"]

output = ([(sub+' '+verb+' '+obj) for sub in subjects for verb in verbs for obj in objects])
for i in output:
  print(i)


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [0]:
# Using  for loop
for sub in subjects:
  for verb in verbs:
    for obj in objects:
      print(sub+''+verb+' '+obj)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indiansplay Baseball
Indiansplay Cricket
Indianswatch Baseball
Indianswatch Cricket


### Task 2:
#### 1. Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

NOTE: The solution shared through Github should contain the source code used and the
screenshot of the output.

In [2]:
# Example of Alexandre- Theophile Vandermonde.
import numpy as np

x = np.array([1, 2, 3, 4])
N = 5
np.vander(x, N)
  

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]])

In [3]:
 x

array([1, 2, 3, 4])

In [5]:
x = list(map(int, input('Enter input with space seperated numbers : ').split()))
n = int(input('Enter n : '))
def vander(x,n):
    output=[]
    for i in range(len(x)):
        dummy=[]
        for j in range(n-1,-1,-1):
            item=x[i]**j
            dummy.append(item)
        output.append(dummy)
    return output
  
print(np.array(vander(x,n)))


Enter input with space seperated numbers : 1 2 3 4
Enter n : 5
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]
