<a href="https://colab.research.google.com/github/roshan-pasha/ineuron/blob/master/Numpy_ineuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
# Example of Alexandre- Theophile Vandermonde.
import numpy as np

x = np.array([1, 2, 3, 4])
N = 5
np.vander(x, N)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]])

In [0]:
x

array([1, 2, 3, 4])

In [0]:
x = list(map(int, input('Enter input with space seperated numbers : ').split()))
n = int(input('Enter n : '))
def vander(x,n):
    output=[]
    for i in range(len(x)):
        dummy=[]
        for j in range(n-1,-1,-1):
            item=x[i]**j
            dummy.append(item)
        output.append(dummy)
    return output
  
print(np.array(vander(x,n)))

Enter input with space seperated numbers : 1 2 3 4
Enter n : 2
[[1 1]
 [2 1]
 [3 1]
 [4 1]]




Problem Statement 2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [16]:
def moving_avg(a, window = 3):
  ret = np.cumsum(a,dtype= float)
  ret[window:] = ret[window:] - ret[:-window]
  return ret[window - 1:] / window
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_avg(a))
numbers = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
print(moving_avg(numbers,window=4))


[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
[25. 35. 45. 55. 65. 75. 85.]
